version: "3.8"

services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - net
    ports:
      - 3306:3306
    env_file:
      - .env
    restart: always

networks:
  net: